/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.oop2.java_project.student;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 이혜리 21.11.12. 강의 목록에서 선택하여 현재 강의 신청 목록에 출력하도록 구현 21.11.13. 수강신청한
 * 학점을계산하도록 만듦. 21.11.14. 수강신청 성공 메세지 출력
 */
public class CourseRegister extends javax.swing.JFrame {

    /**
     * Creates new form CourseRegister
     */
    public CourseRegister() {
        initComponents();
        Total_OUTPUT.setEnabled(false); // 신청 학점란 변경 못하게 막음        
        jTable2.setEnabled(false);
    }

    public CourseRegister(String URL) {
        initComponents();
        setTitle("학생 수강신청");
        this.URL = URL;

        Total_OUTPUT.setEnabled(false); // 신청 학점란 변경 못하게 막음        
        jTable2.setEnabled(false);

    }
    String URL = null;
    String name = null; // 학생 이름
    String num = null; // 학번

    String URL_stcourse = null;

    public CourseRegister(String URL, String name, String num) {
        initComponents();
        setTitle("학생 - 수강신청");
        this.URL = URL;
        this.URL_stcourse = URL + "\\stcourse.txt";
        this.name = name;
        this.num = num;

        //Total_OUTPUT.setEnabled(false); // 신청 학점란 변경 못하게 막음        
        //jTable2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTT_AddCourse = new javax.swing.JButton();
        BUTT_Close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Total_OUTPUT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BUTT_AddCourse.setText("수강신청");
        BUTT_AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_AddCourseActionPerformed(evt);
            }
        });

        BUTT_Close.setText("닫기");
        BUTT_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_CloseActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "강좌번호", "강좌명", "담당학과", "담당교수", "학점", "강의계획내용"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "강좌번호", "강좌명", "담당학과", "담당교수", "학점", "강의계획내용"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("수강신청 총 학점 ");

        Total_OUTPUT.setEditable(false);
        Total_OUTPUT.setToolTipText("");
        Total_OUTPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_OUTPUTActionPerformed(evt);
            }
        });

        jLabel2.setText("학생 수강신청");

        jLabel3.setText("강의목록");

        jLabel4.setText("현재 강의신청 목록");

        jButton1.setText("저장");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("강좌조회");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Total_OUTPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 641, Short.MAX_VALUE)
                        .addComponent(BUTT_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(BUTT_AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton2)))
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Total_OUTPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(BUTT_Close)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 중복되는 강좌번호 및 강좌 이름이 있는지 체크하는 메소드
    void Compare_Lecture_Class() {
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

        for (int i = 0; i < model2.getRowCount(); i++) {
            for (int j = 0; j < model2.getColumnCount(); j++) {
                if (model2.getValueAt(i, j).equals(row[0]) || model2.getValueAt(i, j).equals(row[1])) {
                    ch = -2;
                    break;
                }
            }
            if (ch == -2) {
                break;
            }
        }
    }

    // 강의 목록에서 선택하여 현재 강의 신청 목록에 출력
    int ch = 0; // 체크 변수
    int score_check = 0;
    int sum_result = 0; // 신청 학점
    Object[] row = new Object[6];
    private void BUTT_AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_AddCourseActionPerformed

        TableModel model1 = jTable1.getModel(); // 테이블 저장
        int[] indexs = jTable1.getSelectedRows(); // 테이블에 있는 열 저장

        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

        int sum_temp = 0;

        for (int i = 0; i < indexs.length; i++) {
            if (score_check == 0) {
                row[0] = model1.getValueAt(indexs[i], 0);
                row[1] = model1.getValueAt(indexs[i], 1);
                row[2] = model1.getValueAt(indexs[i], 2);
                row[3] = model1.getValueAt(indexs[i], 3);
                row[4] = model1.getValueAt(indexs[i], 4);
                row[5] = model1.getValueAt(indexs[i], 5);
            }
        }

        // 같은 강좌가 있는 지 비교하기 위함
        Compare_Lecture_Class();

        if (ch == 0) {
            model2.addRow(row);
            for (int i = 0; i < model2.getRowCount(); i++) {
                if (sum_temp < 18) {
                    sum_temp += Integer.parseInt(model2.getValueAt(i, 4).toString());
                }

                //18학점 이상 신청하지 못하게 하기 위함
                if (sum_temp == 18) {
                    score_check = -1;
                }
            }
            sum_result = sum_temp;
            Total_OUTPUT.setText(Integer.toString(sum_result));
            sum_result = 0;
        } else if (score_check == -1) {
            JOptionPane.showMessageDialog(null, "18학점을 초과하셨습니다.");
        } else if (ch == -2) {
            JOptionPane.showMessageDialog(null, "강좌가 중복되었습니다.");
        }
        ch = 0; // 중복된 강좌 클릭 후 중복 아닌 강좌 클릭 시 오류를 해결하기 위한 초기화
    }//GEN-LAST:event_BUTT_AddCourseActionPerformed

    private void BUTT_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_CloseActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
        dispose();
=======
        System.exit(0);
>>>>>>> e4b573a81b8a11f565961714e1ed71f647a64340
    }//GEN-LAST:event_BUTT_CloseActionPerformed

    private void Total_OUTPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_OUTPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_OUTPUTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //학번, 이름 제외 구현 완료
        String filePath = URL_stcourse;

        File file = new File(filePath);

        String s = "/";
        String n = "\n";

        try {
            FileWriter writer = new FileWriter(file, true);
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                writer.write(num);
                writer.write(s);
                writer.write(name);
                for (int j = 0; j < jTable2.getColumnCount(); j++) {
                    writer.write(s);
                    writer.write(jTable2.getValueAt(i, j).toString());
                }
                writer.write(s);
                writer.write("학점");
                writer.write(n);
            }
            writer.flush();
            writer.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "수강신청이 완료되었습니다.");
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    int check = 0; // 강좌 조회 횟수를 1회로 제한하기 위함
    // 강좌조회 중복으로 계속 이어 나가는 문제 해결하기
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (check != -1) {

            String filePath = URL + "\\lectureclass.txt";
            File file = new File(filePath);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            try {
                BufferedReader read = new BufferedReader(new FileReader(file));

                Object[] tableline = read.lines().toArray();

                for (int i = 0; i < tableline.length; i++) {
                    String line = tableline[i].toString().trim();
                    String[] dataRow = line.split("/");

                    ArrayList arr = new ArrayList<>();
                    arr.add(dataRow[0]);
                    arr.add(dataRow[1]);
                    arr.add(dataRow[2]);
                    arr.add(dataRow[3]);
                    arr.add(dataRow[4]);
                    arr.add(dataRow[5]);

                    model.addRow(new Object[]{arr.get(0), arr.get(1), arr.get(2), arr.get(3), arr.get(4), arr.get(5)});
                }
                check = -1;
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "강좌 조회는 1회만 가능합니다.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTT_AddCourse;
    private javax.swing.JButton BUTT_Close;
    private javax.swing.JTextField Total_OUTPUT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
