/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.oop2.java_project;

import cse.oop2.java_project.login.LoginPage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author 정민수
 */
public class First extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    public First() {
        initComponents();
        setTitle("시작 페이지");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BUTT_START = new javax.swing.JButton();
        FileURL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("대학 정보 관리 시스템");

        BUTT_START.setText("시작");
        BUTT_START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_STARTActionPerformed(evt);
            }
        });

        jLabel3.setText("파일경로");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("※ 경로는 info 경로까지만 입력 부탁드립니다.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(FileURL, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BUTT_START, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FileURL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTT_START, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTT_STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_STARTActionPerformed
        // TODO add your handling code here:
        // 버튼을 누르면 로그인 페이지로 이동
        // 시작 전 파일 절대 경로 설정해주기
        // 파일 처리 방식을 사용하기 위해 시작 전 info에 txt 파일을 생성
        String URL = null; // 파일 절대 경로를 입력받기 위한 변수

        if (FileURL.getText().equals("")) { // 절대경로를 입력하지 않았을 경우
            JOptionPane.showMessageDialog(null, "파일처리 방식을 사용하기 위해 파일 절대경로를 입력해주시기 바랍니다.");
        } else {
            URL = FileURL.getText();
            File student = new File(URL + "\\student.txt");
            File professor = new File(URL + "\\professor.txt");
            File class_manager = new File(URL + "\\class_manager.txt");
            File bachelor_manager = new File(URL + "\\bachelor_manager.txt");
            File lectureclass = new File(URL + "\\lectureclass.txt");
            File stcourse = new File(URL + "\\stcourse.txt");

            try {
                // 학생 정보 메모장 생성
                if (student.createNewFile()) {
                    System.out.println("Student File created");
                } else {
                    System.out.println("Student File arlready exists");
                }
                // 교수 정보 메모장 생성
                if (professor.createNewFile()) {
                    System.out.println("Professor File created");
                } else {
                    System.out.println("Professor File arlready exists");
                }
                // 수업 담당자 정보 메모장 생성
                if (class_manager.createNewFile()) {
                    System.out.println("class_manager File created");
                    FileWriter writer;
                    writer = new FileWriter(class_manager, true);
                    writer.write("G000");
                    writer.write("/");
                    writer.write("123456-0000000");
                    writer.write("\n");
                    writer.flush();// 출력은 버퍼에 쌓여있기에 쌓인 버퍼를 목적지로 보내줌
                    writer.close();
                } else {
                    System.out.println("class_manage File arlready exists");
                }
                //  강의, 강좌 정보 메모장 생성
                if (lectureclass.createNewFile()) {
                    System.out.println("lectureclass File created");
                } else {
                    System.out.println("lectureclass File arlready exists");
                }
                // 수강 신청한 내용을 저장하는 메모장 생성
                if (stcourse.createNewFile()) {
                    System.out.println("stcourse File created");
                } else {
                    System.out.println("stcourse File arlready exists");
                }

                // 학사 담당자 정보 메모장 생성 (시작할 때 초기 로그인 아이디 부여, 프로그램 처음 시작 시 학사 담당자 아이디로만 로그인 가능)
                if (bachelor_manager.createNewFile()) {
                    FileWriter writer;
                    writer = new FileWriter(bachelor_manager, true);
                    writer.write("H000");
                    writer.write("/");
                    writer.write("123456-0000000");
                    writer.write("\n");
                    writer.flush();// 출력은 버퍼에 쌓여있기에 쌓인 버퍼를 목적지로 보내줌
                    writer.close();
                    System.out.println("bachelor_manager File created");
                } else {
                    System.out.println("bachelor_manager File arlready exists");
                }

                JOptionPane.showMessageDialog(null, "대학 정보 관리 시스템을 시작하겠습니다.");
                LoginPage login = new LoginPage(URL);
                login.setVisible(true);
                dispose();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "파일 절대 경로가 옳바르지 않습니다. 다시 입력 바랍니다.");
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_BUTT_STARTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTT_START;
    private javax.swing.JTextField FileURL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
